[package]
name = "egui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pipe"
path = "src/main.rs"

[dependencies]
egui = "0.24"
eframe = "0.24"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }
winit = "0.27"
